import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Sidebar from "@/components/sidebar";
import Summery from "@/components/summary";
import Experience from "@/components/experience";
import Contest from "@/components/contest";
import Projects from "@/components/projects";

export default function Home() {
  return (
    <div className="rounded-lg bg-slate-50">
      <Head>
        <title>Mamun-Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <Sidebar />
        <div>
          <div className="bg-[#a89732] h-14 rounded-r-full py-2  text-xl w-72 text-center mt-16">
            MD AL MAMUN MIM
          </div>
          <div className="ml-14 flex-col space-y-4">
          <Summery />
          <Experience />
          <Contest />
          <Projects/>
          </div>
      
        </div>
      </div>
    </div>
  );
}
